### ISSUE TITLE
ChatML中的system数据是怎么用的？

### ISSUE THREAD

**Issue by lucasjinreal** [pleisto/yuren-7b#3]
如题

**Comment by 0xDing** [comment]
在推理的时候可以单独设置system prompt。 参考： https://github.com/pleisto/yuren-baichuan-7b/blob/7633d2ee46527085725c9eb4d2dae3f4619cdcfe/apps/webui/src/webui/utils.py#L335

在训练时，system prompt和user prompt(role: human)一样处理，也就是会用 ignore index id 在 labels 里mask掉，参考：https://github.com/pleisto/yuren-baichuan-7b/blob/7633d2ee46527085725c9eb4d2dae3f4619cdcfe/apps/yuren_trainer/src/yuren_trainer/build_datasets.py#L108

**Comment by lucasjinreal** [comment]
我理解可能跟现在常用的 system_prompt xxx user: xx assistant: 有点像，

**Comment by 0xDing** [comment]
> 我理解可能跟现在常用的 system_prompt xxx user: xx assistant: 有点像，
是的 和chatgpt的system prompt完全等价。

ref: https://github.com/mustvlad/ChatGPT-System-Prompts
